### ISSUE TITLE
News+ stopped syncing today

### ISSUE THREAD

**Issue by mustafa1024m** [Athou/commafeed-newsplus#1]
Hi,
I use News+ extensively, today, it doesn't sync, maybe have something to do with the new tags?

**Comment by Athou** [comment]
Yes indeed, please try the new apk I just uploaded.

**Comment by mustafa1024m** [comment]
It is working perfectly, thank you very much for CommaFeed, the News+ plugin, and your quick response for fixing the problem, I really appreciate your hard work.
Thanks
