### ISSUE TITLE
Self-signed SSL

### ISSUE THREAD

**Issue by marco44** [Athou/commafeed-newsplus#12]
Hi,

I'm hosting commafeed on my own PC, with a self-signed certificate. I cannot sync with it because of "Trust anchor for certification path not found".

Most apps of this kind (such as ttrss-reader) provide an option to accept invalid certificates. Did I miss it in the options ? Or could it be possible to add it ?

Best regards

**Comment by antivirtel** [comment]
I'd say use Let's Encrypt now - it's free SSL cert. @Athou you can probably close this
