### ISSUE TITLE
SSL-HandshakeException

### ISSUE THREAD

**Issue by MichaelRLee** [Athou/commafeed-newsplus#13]
For a few days now, whenever trying to update, the following error message is displayed:

ERROR_UNKNOWN: I/O error: java.security.CertPathValidatorException: Trust anchor for certification path not found.; nested exception is javax.net.ssl.SSL-HandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

An update resolving this, or even just a response if there are no plans to do so would be greatly appreciated.  Thanks!

**Comment by Athou** [comment]
There was an issue with the renewed certificate, the intermediate certificate changed too.
It should be fixed now!
