### ISSUE TITLE
Getting 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by antivirtel** [Athou/commafeed-newsplus#7]
I'm using the https://www.commafeed.com server and the latest Play Store release (1.0). I'm getting 401 UNAUTHORIZED. I've tried to log out/in, and the same.

It was working with 1.0-SNAPSHOT... please fix it!

**Comment by Athou** [comment]
I'll have a look.

**Comment by Athou** [comment]
I can't reproduce :( Are you sure you're using the right login/pass?

**Comment by antivirtel** [comment]
I don't know what was the problem, but it is working right now. Maybe you should check the login/password after its typing, do not let the News+ notify the users with HTTP error 401! 

Thanks!

**Comment by goulu** [comment]
Same problem here and now. I can read https://www.commafeed.com/rest/category/entriesAsFeed?id=starred&apiKey=a060bdd5f1c977aa960861ffb2ca6347d824508b in my browser, but others tools can't access it, such as http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.commafeed.com%2Frest%2Fcategory%2FentriesAsFeed%3Fid%3Dstarred%26apiKey%3Da060bdd5f1c977aa960861ffb2ca6347d824508b which returns a 401...

**Comment by Athou** [comment]
My bad :( This commit should fix it I'll deploy it asap.

Thanks for the report !

**Comment by goulu** [comment]
Thanks a lot for solving this so quickly !
BTW, the validator link above shows several things that could be improved in the feed, one day ...
